/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    

    public static void main(String[] args) {
        var haystack = "a";   
        var needle = "a";

        var index = strStr(haystack, needle);

        System.out.println(index);
    }

    public static int strStr(String haystack, String needle) {
        var haystackChars = haystack.toCharArray();
        var needleChars = needle.toCharArray();

        for(int i = 0; i < haystackChars.length; ++i) {
            var movingIndex = i;
            for(int j = 0; j < needleChars.length; ++j) {

                // needle is longer than remaining characters in haystack
                if(movingIndex > haystackChars.length - 1) {
                    return -1;
                }

                if(haystackChars[movingIndex] != needleChars[j]) {
                    break;
                }

                // If this condition is true, then we have iterated through 
                // all characters in needle successfully; thus needle is present in haystack
                if(j == needleChars.length - 1) {
                    return i;
                }

                movingIndex++;
            }
        }

        return -1;
    }
}
