/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {
        int[] input = {0,1,2,2,3,0,4,2};

        removeElement(input, 2);
        System.out.println(Arrays.toString(input));
    }

    public static int removeElement(int[] nums, int val) {
        var end = nums.length - 1;
        var occurencesOfVal = 0;

        for(int i = 0; i < nums.length; ++i) {
            while(nums[i] == val) {
                // Since we move all of the val to the end of the array,
                // once end < i all entries will be val and we can end looping early
                if(end < i) {
                    break;
                }

                var temp = nums[i];
                nums[i] = nums[end];
                nums[end] = temp;

                end--;
                occurencesOfVal++;
            }
        }


        return nums.length - occurencesOfVal;
    }
}
